Upload thumbnail test & mocking
spknetwork/acela-core pull request #19
Opened 2024-05-25 17:32 UTC by sisygoboom

- create test for thumbnail uploading endpoint
- updates to the mock factory and which modules it affects in different environments:
no longer affects repositories as we're using a replica set in staging anyway
no longer affects staging: ipfs and hive modules, as we need to test these in prod-like environments

2024-05-25 17:46 UTC, Geo25rey requested changes
Why the deleted mocks?

Absolutely no binary files unless 100% necessary.

2024-05-25 17:46 UTC, Geo25rey commented on src/services/uploader/test-resources/test.png
No binary files. We don't need another libxz hack.

2024-05-25 17:46 UTC, Geo25rey commented on src/repositories/video/video.repository.mock.ts
Why is this deleted?

2024-05-25 17:46 UTC, Geo25rey commented on src/repositories/creator/creator.repository.mock.ts
And this?

2024-05-25 19:09 UTC, sisygoboom commented on src/services/uploader/test-resources/test.png
I'd normally agree with you, but in this case, it's 670 bytes, which is barely enough for the image data, never mind a backdoor. Additionally, it's only used in test code.

2024-05-25 19:09 UTC, sisygoboom commented on src/repositories/video/video.repository.mock.ts
I explain in the pr description that we use a replica set in the staging env and locally we run a mongo db via docker compose so there's actually never any need to mock the mongo calls

2024-05-25 19:09 UTC, sisygoboom commented on src/repositories/creator/creator.repository.mock.ts
same reason

2024-05-25 19:47 UTC, Geo25rey commented on src/services/uploader/test-resources/test.png
That's exactly how to xz hack happened. No binaries for tests. Maybe use an svg or something?

2024-05-25 19:48 UTC, Geo25rey commented on src/repositories/video/video.repository.mock.ts
I get that, but what happens when you want to do unit tests that don't rely on the db?

2024-05-25 19:51 UTC, Geo25rey commented on src/services/uploader/test-resources/test.png
You can use [this](https://www.npmjs.com/package/svg2png-wasm) if you really need a png

2024-05-25 22:59 UTC, sisygoboom commented on src/services/uploader/test-resources/test.png
That package literally needs to execute a mystery 2mb wasm binary in order to work, I'd argue much larger security risk
![image](https://github.com/spknetwork/acela-core/assets/7293419/3bfb2a77-03fb-4937-91bc-1fd854308a84)
https://github.com/ssssota/svg2png-wasm?tab=readme-ov-file#nodejs

2024-05-25 23:08 UTC, sisygoboom commented on src/repositories/video/video.repository.mock.ts
Very valid point, sometimes someone might need to mock out a function to perform a test if they don't want to set up the test in a way which simulates MongoDB in memory. However (and this is just my opinion) unit tests should test pure functions, if there are db calls in a function it becomes an integration test. in which case it should be verified the items are being correctly inserted into in-memory db

2024-05-25 23:10 UTC, sisygoboom commented on src/services/uploader/test-resources/test.png
I'd also like to add that it seems the svgs in their codebase are actually base64 encoded pngs with SVG wrappers https://github.com/ssssota/svg2png-wasm/blob/main/site/static/parrot.svg?short_path=4ff033b

2024-05-25 23:48 UTC, Geo25rey commented on src/services/uploader/test-resources/test.png
Here's a pure JS implementation https://www.npmjs.com/package/@michaelheerklotz/svgexport

2024-05-25 23:49 UTC, Geo25rey commented on src/repositories/video/video.repository.mock.ts
I don't think it hurts to leave it in.

2024-05-26 03:30 UTC, Geo25rey approved these changes
LGTM

2024-05-26 10:36 UTC, merged